.TH "[" "1" "2026-07-28" "BNU 9.11" "BNU Commands"
.SH NAME
[ \- evaluate a conditional expression
.SH SYNOPSIS
.B [
\fI\,EXPRESSION \/\fR]
.br
.B [ ]
.br
.B [
\fI\,OPTION\/\fR
.SH DESCRIPTION
.B [
is BNU's alternate form of
.BR test (1).
The closing bracket must be a separate final operand.  To request help or
version information, omit the closing bracket and use
.B [ --help
or
.BR "[ --version" .
.SH "REPORTING BUGS"
Report BNU bugs at <https://github.com/Soccera1/bnu/issues>.
.SH "SEE ALSO"
.BR test (1)
.PP
BNU documentation is available locally via: info \(aq(bnu) test invocation\(aq
