.\" Adapted for BNU from the GNU Coreutils 9.11 manual page; see doc/README.md.
.TH DIRNAME "1" "2026-07-28" "BNU 9.11" "BNU Commands"
.SH NAME
dirname \- strip last component from file name
.SH SYNOPSIS
.B dirname
[\fI\,OPTION\/\fR] \fI\,NAME\/\fR...
.SH DESCRIPTION
.\" This page is derived from GNU Coreutils documentation.
This page documents BNU, an independent Bun implementation compatible with
GNU Coreutils 9.11.
.PP
Output each NAME with its last non\-slash component and trailing slashes
removed; if NAME contains no /'s, output '.' (meaning the current directory).
.TP
\X'tty: link https://www.gnu.org/software/coreutils/manual/coreutils.html#dirname-z'\fB\-z, \-\-zero\fP\X'tty: link'
end each output line with NUL, not newline
.TP
\X'tty: link https://www.gnu.org/software/coreutils/dirname#dirname--help'\fB\-\-help\fP\X'tty: link'
display this help and exit
.TP
\X'tty: link https://www.gnu.org/software/coreutils/dirname#dirname--version'\fB\-\-version\fP\X'tty: link'
output version information and exit
.SH EXAMPLES
.TP
dirname /usr/bin/
\-> "/usr"
.TP
dirname dir1/str dir2/str
\-> "dir1" followed by "dir2"
.TP
dirname stdio.h
\-> "."
.SH AUTHORS
Upstream GNU Coreutils documentation authors:
Written by David MacKenzie and Jim Meyering.
.br
Adapted for BNU; the BNU implementation is independent.
.SH "REPORTING BUGS"
Report BNU bugs at <https://github.com/Soccera1/bnu/issues>.
.br
For upstream GNU Coreutils, see <https://www.gnu.org/software/coreutils/>.
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
This manual page was adapted for BNU in 2026.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
\fBbasename\fP(1), \fBreadlink\fP(1)
.PP
.br
Upstream documentation <https://www.gnu.org/software/coreutils/dirname>
.br
BNU documentation is available locally via: info \(aq(bnu) dirname invocation\(aq
