.\" Adapted for BNU from the GNU Coreutils 9.11 manual page; see doc/README.md.
.TH FACTOR "1" "2026-07-28" "BNU 9.11" "BNU Commands"
.SH NAME
factor \- factor numbers
.SH SYNOPSIS
.B factor
[\fI\,OPTION\/\fR] [\fI\,NUMBER\/\fR]...
.SH DESCRIPTION
.\" This page is derived from GNU Coreutils documentation.
This page documents BNU, an independent Bun implementation compatible with
GNU Coreutils 9.11.
.PP
Print the prime factors of each specified integer NUMBER.  If none
are specified on the command line, read them from standard input.
.TP
\X'tty: link https://www.gnu.org/software/coreutils/manual/coreutils.html#factor-h'\fB\-h, \-\-exponents\fP\X'tty: link'
print repeated factors in form p^e unless e is 1
.TP
\X'tty: link https://www.gnu.org/software/coreutils/factor#factor--help'\fB\-\-help\fP\X'tty: link'
display this help and exit
.TP
\X'tty: link https://www.gnu.org/software/coreutils/factor#factor--version'\fB\-\-version\fP\X'tty: link'
output version information and exit
.SH AUTHORS
Upstream GNU Coreutils documentation authors:
Written by Paul Rubin, Torbjorn Granlund, and Niels Moller.
.br
Adapted for BNU; the BNU implementation is independent.
.SH "REPORTING BUGS"
Report BNU bugs at <https://github.com/Soccera1/bnu/issues>.
.br
For upstream GNU Coreutils, see <https://www.gnu.org/software/coreutils/>.
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
This manual page was adapted for BNU in 2026.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
Upstream documentation <https://www.gnu.org/software/coreutils/factor>
.br
BNU documentation is available locally via: info \(aq(bnu) factor invocation\(aq
