.TH GINSTALL "1" "2026-07-28" "BNU 9.11" "BNU Commands"
.SH NAME
ginstall \- copy files and set attributes
.SH SYNOPSIS
.B ginstall
[\fI\,OPTION\/\fR]... [\fI\,OPERAND\/\fR]...
.SH DESCRIPTION
.B ginstall
is a BNU alias for
.BR install (1).
It accepts the same invocation forms and options.  The alias is provided for
environments where the unprefixed name is occupied by another program.
.SH "REPORTING BUGS"
Report BNU bugs at <https://github.com/Soccera1/bnu/issues>.
.SH "SEE ALSO"
.BR install (1)
.PP
BNU documentation is available locally via: info \(aq(bnu) install invocation\(aq
