.\" Adapted for BNU from the GNU Coreutils 9.11 manual page; see doc/README.md.
.TH HOSTID "1" "2026-07-28" "BNU 9.11" "BNU Commands"
.SH NAME
hostid \- print the numeric identifier for the current host
.SH SYNOPSIS
.B hostid
[\fI\,OPTION\/\fR]
.SH DESCRIPTION
.\" This page is derived from GNU Coreutils documentation.
This page documents BNU, an independent Bun implementation compatible with
GNU Coreutils 9.11.
.PP
Print the numeric identifier (in hexadecimal) for the current host.
.TP
\X'tty: link https://www.gnu.org/software/coreutils/hostid#hostid--help'\fB\-\-help\fP\X'tty: link'
display this help and exit
.TP
\X'tty: link https://www.gnu.org/software/coreutils/hostid#hostid--version'\fB\-\-version\fP\X'tty: link'
output version information and exit
.SH AUTHORS
Upstream GNU Coreutils documentation authors:
Written by Jim Meyering.
.br
Adapted for BNU; the BNU implementation is independent.
.SH "REPORTING BUGS"
Report BNU bugs at <https://github.com/Soccera1/bnu/issues>.
.br
For upstream GNU Coreutils, see <https://www.gnu.org/software/coreutils/>.
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
This manual page was adapted for BNU in 2026.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
\fBgethostid\fP(3)
.PP
.br
Upstream documentation <https://www.gnu.org/software/coreutils/hostid>
.br
BNU documentation is available locally via: info \(aq(bnu) hostid invocation\(aq
