.\" Adapted for BNU from the GNU Coreutils 9.11 manual page; see doc/README.md.
.TH LOGNAME "1" "2026-07-28" "BNU 9.11" "BNU Commands"
.SH NAME
logname \- print user\'s login name
.SH SYNOPSIS
.B logname
[\fI\,OPTION\/\fR]
.SH DESCRIPTION
.\" This page is derived from GNU Coreutils documentation.
This page documents BNU, an independent Bun implementation compatible with
GNU Coreutils 9.11.
.PP
Print the user's login name.
.TP
\X'tty: link https://www.gnu.org/software/coreutils/logname#logname--help'\fB\-\-help\fP\X'tty: link'
display this help and exit
.TP
\X'tty: link https://www.gnu.org/software/coreutils/logname#logname--version'\fB\-\-version\fP\X'tty: link'
output version information and exit
.SH AUTHORS
Upstream GNU Coreutils documentation authors:
Written by David MacKenzie.
.br
Adapted for BNU; the BNU implementation is independent.
.SH "REPORTING BUGS"
Report BNU bugs at <https://github.com/Soccera1/bnu/issues>.
.br
For upstream GNU Coreutils, see <https://www.gnu.org/software/coreutils/>.
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
This manual page was adapted for BNU in 2026.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
\fBgetlogin\fP(3)
.PP
.br
Upstream documentation <https://www.gnu.org/software/coreutils/logname>
.br
BNU documentation is available locally via: info \(aq(bnu) logname invocation\(aq
