.\" Adapted for BNU from the GNU Coreutils 9.11 manual page; see doc/README.md.
.TH PWD "1" "2026-07-28" "BNU 9.11" "BNU Commands"
.SH NAME
pwd \- print name of current/working directory
.SH SYNOPSIS
.B pwd
[\fI\,OPTION\/\fR]...
.SH DESCRIPTION
.\" This page is derived from GNU Coreutils documentation.
This page documents BNU, an independent Bun implementation compatible with
GNU Coreutils 9.11.
.PP
Print the full filename of the current working directory.
.TP
\X'tty: link https://www.gnu.org/software/coreutils/manual/coreutils.html#pwd-L'\fB\-L, \-\-logical\fP\X'tty: link'
use PWD from environment, even if it contains symlinks
.TP
\X'tty: link https://www.gnu.org/software/coreutils/manual/coreutils.html#pwd-P'\fB\-P, \-\-physical\fP\X'tty: link'
resolve all symlinks
.TP
\X'tty: link https://www.gnu.org/software/coreutils/pwd#pwd--help'\fB\-\-help\fP\X'tty: link'
display this help and exit
.TP
\X'tty: link https://www.gnu.org/software/coreutils/pwd#pwd--version'\fB\-\-version\fP\X'tty: link'
output version information and exit
.PP
If no option is specified, \fB\-P\fR is assumed.
.PP
Your shell may have its own version of pwd, which usually supersedes
the version described here.  Please refer to your shell's documentation
for details about the options it supports.
.SH AUTHORS
Upstream GNU Coreutils documentation authors:
Written by Jim Meyering.
.br
Adapted for BNU; the BNU implementation is independent.
.SH "REPORTING BUGS"
Report BNU bugs at <https://github.com/Soccera1/bnu/issues>.
.br
For upstream GNU Coreutils, see <https://www.gnu.org/software/coreutils/>.
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
This manual page was adapted for BNU in 2026.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
\fBgetcwd\fP(3)
.PP
.br
Upstream documentation <https://www.gnu.org/software/coreutils/pwd>
.br
BNU documentation is available locally via: info \(aq(bnu) pwd invocation\(aq
