.\" Adapted for BNU from the GNU Coreutils 9.11 manual page; see doc/README.md.
.TH REALPATH "1" "2026-07-28" "BNU 9.11" "BNU Commands"
.SH NAME
realpath \- print the resolved path
.SH SYNOPSIS
.B realpath
[\fI\,OPTION\/\fR]... \fI\,FILE\/\fR...
.SH DESCRIPTION
.\" This page is derived from GNU Coreutils documentation.
This page documents BNU, an independent Bun implementation compatible with
GNU Coreutils 9.11.
.PP
Print the resolved absolute file name.
.TP
\X'tty: link https://www.gnu.org/software/coreutils/manual/coreutils.html#realpath-E'\fB\-E, \-\-canonicalize\fP\X'tty: link'
all but the last component must exist (default)
.TP
\X'tty: link https://www.gnu.org/software/coreutils/manual/coreutils.html#realpath-e'\fB\-e, \-\-canonicalize\-existing\fP\X'tty: link'
all components of the path must exist
.TP
\X'tty: link https://www.gnu.org/software/coreutils/manual/coreutils.html#realpath-m'\fB\-m, \-\-canonicalize\-missing\fP\X'tty: link'
no path components need exist or be a directory
.TP
\X'tty: link https://www.gnu.org/software/coreutils/manual/coreutils.html#realpath-L'\fB\-L, \-\-logical\fP\X'tty: link'
resolve '..' components before symlinks
.TP
\X'tty: link https://www.gnu.org/software/coreutils/manual/coreutils.html#realpath-P'\fB\-P, \-\-physical\fP\X'tty: link'
resolve symlinks as encountered (default)
.TP
\X'tty: link https://www.gnu.org/software/coreutils/manual/coreutils.html#realpath-q'\fB\-q, \-\-quiet\fP\X'tty: link'
suppress most error messages
.TP
\X'tty: link https://www.gnu.org/software/coreutils/manual/coreutils.html#realpath--relative-to'\fB\-\-relative\-to=DIR\fP\X'tty: link'
print the resolved path relative to DIR
.TP
\X'tty: link https://www.gnu.org/software/coreutils/manual/coreutils.html#realpath--relative-base'\fB\-\-relative\-base=DIR\fP\X'tty: link'
print absolute paths unless paths below DIR
.TP
\X'tty: link https://www.gnu.org/software/coreutils/manual/coreutils.html#realpath-s'\fB\-s, \-\-strip, \-\-no\-symlinks\fP\X'tty: link'
don't expand symlinks
.TP
\X'tty: link https://www.gnu.org/software/coreutils/manual/coreutils.html#realpath-z'\fB\-z, \-\-zero\fP\X'tty: link'
end each output line with NUL, not newline
.TP
\X'tty: link https://www.gnu.org/software/coreutils/realpath#realpath--help'\fB\-\-help\fP\X'tty: link'
display this help and exit
.TP
\X'tty: link https://www.gnu.org/software/coreutils/realpath#realpath--version'\fB\-\-version\fP\X'tty: link'
output version information and exit
.SH AUTHORS
Upstream GNU Coreutils documentation authors:
Written by Padraig Brady.
.br
Adapted for BNU; the BNU implementation is independent.
.SH "REPORTING BUGS"
Report BNU bugs at <https://github.com/Soccera1/bnu/issues>.
.br
For upstream GNU Coreutils, see <https://www.gnu.org/software/coreutils/>.
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
This manual page was adapted for BNU in 2026.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
\fBreadlink\fP(1), \fBreadlink\fP(2), \fBrealpath\fP(3)
.PP
.br
Upstream documentation <https://www.gnu.org/software/coreutils/realpath>
.br
BNU documentation is available locally via: info \(aq(bnu) realpath invocation\(aq
