.\" Adapted for BNU from the GNU Coreutils 9.11 manual page; see doc/README.md.
.TH TSORT "1" "2026-07-28" "BNU 9.11" "BNU Commands"
.SH NAME
tsort \- perform topological sort
.SH SYNOPSIS
.B tsort
[\fI\,OPTION\/\fR] [\fI\,FILE\/\fR]
.SH DESCRIPTION
.\" This page is derived from GNU Coreutils documentation.
This page documents BNU, an independent Bun implementation compatible with
GNU Coreutils 9.11.
.PP
Write totally ordered list consistent with the partial ordering in FILE.
.PP
With no FILE, or when FILE is \-, read standard input.
.TP
\X'tty: link https://www.gnu.org/software/coreutils/tsort#tsort--help'\fB\-\-help\fP\X'tty: link'
display this help and exit
.TP
\X'tty: link https://www.gnu.org/software/coreutils/tsort#tsort--version'\fB\-\-version\fP\X'tty: link'
output version information and exit
.SH AUTHORS
Upstream GNU Coreutils documentation authors:
Written by Mark Kettenis.
.br
Adapted for BNU; the BNU implementation is independent.
.SH "REPORTING BUGS"
Report BNU bugs at <https://github.com/Soccera1/bnu/issues>.
.br
For upstream GNU Coreutils, see <https://www.gnu.org/software/coreutils/>.
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
This manual page was adapted for BNU in 2026.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
Upstream documentation <https://www.gnu.org/software/coreutils/tsort>
.br
BNU documentation is available locally via: info \(aq(bnu) tsort invocation\(aq
