.\" Adapted for BNU from the GNU Coreutils 9.11 manual page; see doc/README.md.
.TH UNLINK "1" "2026-07-28" "BNU 9.11" "BNU Commands"
.SH NAME
unlink \- call the unlink function to remove the specified file
.SH SYNOPSIS
.B unlink
\fI\,FILE\/\fR
.br
.B unlink
\fI\,OPTION\/\fR
.SH DESCRIPTION
.\" This page is derived from GNU Coreutils documentation.
This page documents BNU, an independent Bun implementation compatible with
GNU Coreutils 9.11.
.PP
Call the unlink function to remove the specified FILE.
.TP
\X'tty: link https://www.gnu.org/software/coreutils/unlink#unlink--help'\fB\-\-help\fP\X'tty: link'
display this help and exit
.TP
\X'tty: link https://www.gnu.org/software/coreutils/unlink#unlink--version'\fB\-\-version\fP\X'tty: link'
output version information and exit
.SH AUTHORS
Upstream GNU Coreutils documentation authors:
Written by Michael Stone.
.br
Adapted for BNU; the BNU implementation is independent.
.SH "REPORTING BUGS"
Report BNU bugs at <https://github.com/Soccera1/bnu/issues>.
.br
For upstream GNU Coreutils, see <https://www.gnu.org/software/coreutils/>.
.SH COPYRIGHT
Copyright \(co 2026 Free Software Foundation, Inc.
.br
This manual page was adapted for BNU in 2026.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
\fBunlink\fP(2)
.PP
.br
Upstream documentation <https://www.gnu.org/software/coreutils/unlink>
.br
BNU documentation is available locally via: info \(aq(bnu) unlink invocation\(aq
