// Help for command families beyond GNU Coreutils. The accepted option subsets
// and runtime dependencies are documented in docs/extended-utilities.md.
const entry = (name, operands, description, options) =>
    ({usage: `Usage: ${name} ${operands}`, description, options});
const gzipOptions = [
  "-c, --stdout", "-d, --decompress", "-f, --force", "-k, --keep", "-l, --list", "-n, --no-name",
  "-N, --name", "-q, --quiet", "-r, --recursive", "-S, --suffix=SUFFIX", "-t, --test",
  "-v, --verbose", "-1, --fast ... -9, --best"
];
export const EXTENDED_HELP = {
  grep: entry("grep", "[OPTION]... PATTERNS [FILE]...", "Print lines that match patterns. Read standard input when FILE is omitted or '-'.", ["-G, --basic-regexp", "-E, --extended-regexp", "-F, --fixed-strings", "-P, --perl-regexp (requires libpcre2-8)", "-e, --regexp=PATTERN", "-f, --file=FILE", "-i, --ignore-case", "-v, --invert-match", "-w, --word-regexp", "-x, --line-regexp", "-n, --line-number", "-b, --byte-offset", "-H, --with-filename", "-h, --no-filename", "-c, --count", "-l, --files-with-matches", "-L, --files-without-match", "-q, --quiet", "-s, --no-messages", "-o, --only-matching", "-m, --max-count=NUM", "-A NUM, --after-context=NUM", "-B NUM, --before-context=NUM", "-C NUM, --context=NUM", "-r, --recursive", "-R, --dereference-recursive", "--include=GLOB, --exclude=GLOB, --exclude-dir=GLOB", "--exclude-from=FILE", "--label=LABEL", "--group-separator=STRING, --no-group-separator", "-d, --directories={read|recurse|skip}", "-D, --devices={read|skip}", "--binary-files={binary|text|without-match}", "-a, --text", "-I (ignore binary files)", "-z, --null-data", "-Z, --null", "--color[={always|auto|never}], --colour[=WHEN]"]),
  sed: entry("sed", "[OPTION]... {SCRIPT | -e SCRIPT | -f SCRIPTFILE} [FILE]...", "Transform input using an editing script.", ["-n, --quiet, --silent", "-e, --expression=SCRIPT", "-f, --file=SCRIPTFILE", "-E, -r, --regexp-extended", "-i[SUFFIX], --in-place[=SUFFIX]", "-s, --separate", "-z, --null-data", "-u, --unbuffered", "-l, --line-length=NUM", "--sandbox (disable file reading and writing commands)", "--follow-symlinks (with --in-place)"]),
  awk: entry("awk", "[OPTION]... 'PROGRAM' [FILE]...", "Scan records and execute pattern/action programs.", ["-F FS, --field-separator=FS", "-v VAR=VALUE, --assign=VAR=VALUE", "-f FILE, --file=FILE", "-e PROGRAM, --source=PROGRAM"]),
  diff: entry("diff", "[OPTION]... FILE1 FILE2", "Compare files or directory trees; exit 1 for differences and 2 for errors.", ["-u, -U NUM, --unified[=NUM]", "-c, -C NUM, --context[=NUM]", "--normal", "-e, --ed", "-n, --rcs", "-y, --side-by-side", "-W NUM, --width=NUM", "--left-column, --suppress-common-lines", "-r, --recursive", "-N, --new-file", "-q, --brief", "-s, --report-identical-files", "-i, --ignore-case", "-b, --ignore-space-change", "-w, --ignore-all-space", "-B, --ignore-blank-lines", "-E, --ignore-tab-expansion", "-I REGEXP, --ignore-matching-lines=REGEXP", "-x GLOB, -X FILE", "-L LABEL", "--strip-trailing-cr", "--no-dereference"]),
  cmp: entry("cmp", "[OPTION]... FILE1 [FILE2 [SKIP1 [SKIP2]]]", "Compare bytes; exit 1 for differences and 2 for errors.", ["-b, --print-bytes", "-l, --verbose", "-s, --silent", "-i SKIP[:SKIP], --ignore-initial=SKIP[:SKIP]", "-n LIMIT, --bytes=LIMIT"]),
  sdiff: entry("sdiff", "[OPTION]... FILE1 FILE2", "Display file differences side by side.", ["-w NUM, --width=NUM", "-s, --suppress-common-lines", "-l, --left-column", "-i, --ignore-case", "-b, --ignore-space-change", "-W, --ignore-all-space", "-B, --ignore-blank-lines", "-E, --ignore-tab-expansion"]),
  diff3: entry("diff3", "[OPTION]... MINE OLDER YOURS", "Compare three files or merge changes relative to OLDER.", ["-m, --merge", "-A, --show-all", "-e, --ed", "-E, --show-overlap", "-x, --overlap-only", "-X", "-3, --easy-only", "-L LABEL, --label=LABEL", "-a, --text"]),
  patch: entry("patch", "[OPTION]... [ORIGINAL [PATCHFILE]]", "Apply normal, unified or context diffs to files.", ["-p NUM, --strip=NUM", "-d DIR, --directory=DIR", "-i FILE, --input=FILE", "-R, --reverse", "--dry-run", "-b, --backup", "-z SUFFIX, --suffix=SUFFIX", "-V STYLE, --version-control=STYLE", "-F NUM, --fuzz=NUM", "-l, --ignore-whitespace", "-o FILE, --output=FILE", "-r FILE, --reject-file=FILE", "-E, --remove-empty-files", "-s, --silent", "-N, --forward", "-t, --batch", "-f, --force", "-u, --unified", "-c, --context", "-n, --normal"]),
  tar: entry("tar", "[OPTION]... [FILE]...", "Create, list, extract, compare, append, update, concatenate or delete members of tar archives.", ["-c, --create", "-x, --extract", "-t, --list", "-r, --append", "-u, --update", "-d, --diff", "-A, --concatenate", "--delete", "-f, --file=ARCHIVE", "-C, --directory=DIR", "-z, --gzip", "-a, --auto-compress", "-v, --verbose", "-T, --files-from=FILE", "-X, --exclude-from=FILE", "--exclude=PATTERN", "--null", "--strip-components=NUMBER", "--format=FORMAT (ustar, pax, posix)", "-b, --blocking-factor=BLOCKS", "-h, --dereference", "--no-recursion", "--wildcards", "-k, --keep-old-files", "--skip-old-files", "-p, --same-permissions", "-O, --to-stdout", "-m, --touch", "--same-owner"]),
  gzip: entry("gzip", "[OPTION]... [FILE]...", "Compress or decompress gzip streams and files.", gzipOptions),
  gunzip: entry("gunzip", "[OPTION]... [FILE]...", "Decompress gzip streams and files.", gzipOptions),
  zcat: entry("zcat", "[OPTION]... [FILE]...", "Decompress gzip data to standard output.", gzipOptions),
  cpio: entry("cpio", "{-o|-i|-p|-t} [OPTION]... [PATTERN|DIRECTORY]...", "Copy files into and out of archives, or copy them to a directory.", ["-o, --create", "-i, --extract", "-p, --pass-through", "-t, --list", "-H, --format=FORMAT (bin, odc, newc, crc, tar, ustar)", "-F, --file=ARCHIVE", "-I ARCHIVE, -O ARCHIVE", "-D, --directory=DIR", "-0, --null", "-d, --make-directories", "-m, --preserve-modification-time", "-u, --unconditional", "-a, --reset-access-time", "-L, --dereference", "-l, --link", "-A, --append", "-c (odc)", "-B (5120-byte blocks)", "-C, --io-size=BYTES", "--block-size=BLOCKS", "-E, --pattern-file=FILE", "-f, --nonmatching", "-v, --verbose", "-V, --dot", "--quiet", "--to-stdout", "--only-verify-crc", "--no-absolute-filenames"]),
  wget: entry("wget", "[OPTION]... URL...", "Download HTTP and HTTPS resources, following redirects and streaming response bodies to files.", ["-O, --output-document=FILE", "-P, --directory-prefix=DIR", "-q, --quiet", "-c, --continue", "-N, --timestamping", "-S, --server-response", "-t, --tries=NUMBER", "-T, --timeout=SECONDS", "-U, --user-agent=AGENT", "-i, --input-file=FILE", "-o, --output-file=FILE", "-a, --append-output=FILE", "--header=HEADER", "--post-data=DATA, --post-file=FILE", "--method=METHOD, --body-data=DATA, --body-file=FILE", "--user=USER, --password=PASSWORD", "--max-redirect=NUMBER", "--no-clobber", "--spider", "--content-disposition", "--trust-server-names", "--no-check-certificate", "--no-proxy", "--save-headers"]),
  ar: entry("ar", "[dmpqrstx][abcDfilosSuUv] ARCHIVE [MEMBER]...", "Create, inspect, update or extract Unix archives with a linker symbol index.", ["d delete, m move, p print, q append, r replace, s index, t list, x extract", "a/b/i POSITION insert after/before member", "c suppress creation message", "D deterministic metadata (default), U preserve metadata", "S omit symbol index", "u update newer members", "v verbose"]),
  ranlib: entry("ranlib", "[OPTION]... ARCHIVE...", "Generate a linker symbol index for each archive.", ["-D deterministic metadata (default)", "-U preserve metadata", "-t refresh index"]),
  as: entry("as", "[OPTION]... [FILE]...", "Assemble source into ELF, PE/COFF or Mach-O objects using LLVM's native API.", ["-o FILE", "--32, --64", "--target=TRIPLE", "--mcpu=CPU, --march=CPU", "--mattr=FEATURES", "--defsym=NAME=VALUE", "-g (emit an initial source location)", "-W (suppress warnings)", "--fatal-warnings"]),
  ld: entry("ld", "[OPTION]... FILE...", "Link x86-64 and AArch64 objects and archives into static ELF, PE or Mach-O executables.", ["-o FILE, --output=FILE", "-e SYMBOL, --entry=SYMBOL", "-L DIRECTORY, --library-path=DIRECTORY", "-l LIBRARY, --library=LIBRARY", "-m EMULATION, --emulation=EMULATION", "--oformat=FORMAT", "--arch=ARCH", "--whole-archive, --no-whole-archive", "-u SYMBOL, --undefined=SYMBOL", "-Map FILE, --map=FILE", "-M, --print-map", "--image-base=ADDRESS", "--subsystem=NAME", "--stack=BYTES", "-static, --static", "-s, --strip-all"]),
  nm: entry("nm", "[OPTION]... [FILE]...", "List symbols in ELF, PE/COFF, Mach-O and archive files.", ["-a, --debug-syms", "-A, -o, --print-file-name", "-g, --extern-only", "-u, --undefined-only", "-U, --defined-only", "-n, -v, --numeric-sort", "-p, --no-sort", "-r, --reverse-sort", "-S, --print-size", "--size-sort", "-D, --dynamic", "-C, --demangle", "-P, --portability", "-j, --just-symbols", "-t, --radix={x|d|o}", "-f, --format={bsd|posix|sysv|just-symbols}"]),
  objdump: entry("objdump", "OPTION... FILE...", "Display object headers, sections, symbols, relocations and disassembled instructions.", ["-a, --archive-headers", "-f, --file-headers", "-h, --section-headers", "-p, --private-headers", "-x, --all-headers", "-t, --syms", "-T, --dynamic-syms", "-r, --reloc", "-R, --dynamic-reloc", "-s, --full-contents", "-d, --disassemble", "-D, --disassemble-all", "-j, --section=NAME", "-C, --demangle", "-M, --disassembler-options={intel|att}", "--start-address=ADDRESS, --stop-address=ADDRESS", "--no-show-raw-insn"]),
  readelf: entry("readelf", "OPTION... ELF-FILE...", "Display ELF headers, symbols, relocations, dynamic entries and notes.", ["-a, --all", "-h, --file-header", "-l, --program-headers", "-S, --section-headers", "-e, --headers", "-s, --symbols", "--dyn-syms", "-r, --relocs", "-d, --dynamic", "-n, --notes", "-x, --hex-dump=SECTION", "-p, --string-dump=SECTION", "-W, --wide"]),
  objcopy: entry("objcopy", "[OPTION]... INPUT [OUTPUT]", "Copy or transform ELF, PE/COFF, Mach-O objects and archives.", ["-I, --input-target=TARGET", "-O, --output-target=TARGET", "-j, --only-section=NAME", "-R, --remove-section=NAME", "-S, --strip-all", "-g, --strip-debug", "--strip-unneeded", "--only-keep-debug (ELF)", "-N, --strip-symbol=NAME (ELF)", "--add-section=NAME=FILE (ELF)", "--update-section=NAME=FILE (ELF)", "--dump-section=NAME=FILE", "--rename-section=OLD=NEW", "--gap-fill=BYTE", "-p, --preserve-dates"]),
  strip: entry("strip", "[OPTION]... FILE...", "Remove symbols or debugging information from objects and archives.", ["-s, --strip-all (default)", "-g, -S, -d, --strip-debug", "--strip-unneeded", "--only-keep-debug (ELF)", "-R, --remove-section=NAME", "-N, --strip-symbol=NAME (ELF)", "-o, --output=FILE", "-p, --preserve-dates", "-v, --verbose"]),
  size: entry("size", "[OPTION]... [FILE]...", "Report section sizes for objects and archives.", ["-A, -B, -G, --format={sysv|berkeley|gnu}", "-d, -o, -x, --radix={10|8|16}", "-t, --totals"]),
  strings: entry("strings", "[OPTION]... [FILE]...", "Print sequences of printable characters in binary files.", ["-a, --all", "-d, --data", "-n, --bytes=NUMBER", "-f, --print-file-name", "-t, --radix={o|x|d}", "-o", "-e, --encoding={s|S|b|l|B|L}", "-w, --include-all-whitespace", "-s, --output-separator=STRING"]),
  "c++filt": entry("c++filt", "[OPTION]... [NAME]...", "Demangle Itanium ABI C++ symbols, reading standard input when NAME is omitted.", ["-n, --no-strip-underscore", "-_, --strip-underscore", "-p, --no-params", "-s, --format={auto|gnu-v3}", "-t, --types"]),
  addr2line: entry("addr2line", "[OPTION]... [ADDRESS]...", "Translate ELF, PE/COFF and Mach-O addresses using DWARF 2–5. Read addresses from standard input when omitted; the default object is a.out.", ["-e, --exe=FILE", "-f, --functions", "-C, --demangle", "-a, --addresses", "-p, --pretty-print", "-s, --basenames", "-i, --inlines", "-j, --section=NAME", "-b, --target=FORMAT"]),
  elfedit: entry("elfedit", "[OPTION]... ELF-FILE...", "Update ELF machine, type, OS ABI and ABI version fields.", ["--input-mach=MACHINE, --output-mach=MACHINE", "--input-type=TYPE, --output-type=TYPE", "--input-osabi=ABI, --output-osabi=ABI", "--input-abiversion=VERSION, --output-abiversion=VERSION"]),
};
