export const HASH_HELP_OPTIONS = ["--binary", "--check", "--ignore-missing", "--quiet", "--status", "--strict", "--tag", "--text", "--warn", "--zero", "-b", "-c", "-t", "-w", "-z"];

export const B2SUM_HELP_OPTIONS = ["--binary", "--check", "--ignore-missing", "--length", "--quiet", "--status", "--strict", "--tag", "--text", "--warn", "--zero", "-b", "-c", "-l", "-t", "-w", "-z"];

export const BASE_ENCODING_HELP_OPTIONS = ["--decode", "--ignore-garbage", "--wrap", "-d", "-i", "-w"];

export const COMMAND_HELP_OPTIONS = {
  basename: ["--multiple", "--suffix", "--zero", "-a", "-s", "-z"],
  base32: BASE_ENCODING_HELP_OPTIONS,
  base64: BASE_ENCODING_HELP_OPTIONS,
  basenc: ["--base16", "--base2lsbf", "--base2msbf", "--base32", "--base32hex", "--base58", "--base64", "--base64url", "--decode", "--ignore-garbage", "--wrap", "--z85", "-d", "-i", "-w"],
  b2sum: B2SUM_HELP_OPTIONS,
  cat: ["--number", "--number-nonblank", "--show-all", "--show-ends", "--show-nonprinting", "--show-tabs", "--squeeze-blank", "-A", "-E", "-T", "-b", "-e", "-n", "-s", "-t", "-u", "-v"],
  chcon: ["--dereference", "--no-dereference", "--no-preserve-root", "--preserve-root", "--range", "--recursive", "--reference", "--role", "--type", "--user", "--verbose", "-R", "-h", "-l", "-r", "-t", "-u", "-v"],
  chmod: ["--changes", "--dereference", "--no-dereference", "--no-preserve-root", "--preserve-root", "--quiet", "--recursive", "--reference", "--silent", "--verbose", "-H", "-L", "-P", "-R", "-c", "-f", "-h", "-v"],
  chown: ["--changes", "--dereference", "--from", "--no-dereference", "--no-preserve-root", "--preserve-root", "--quiet", "--recursive", "--reference", "--silent", "--verbose", "-H", "-L", "-P", "-R", "-c", "-f", "-h", "-v"],
  chgrp: ["--changes", "--dereference", "--from", "--no-dereference", "--no-preserve-root", "--preserve-root", "--quiet", "--recursive", "--reference", "--silent", "--verbose", "-H", "-L", "-P", "-R", "-c", "-f", "-h", "-v"],
  chroot: ["--groups", "--skip-chdir", "--userspec"],
  cksum: ["--algorithm", "--base64", "--check", "--debug", "--ignore-missing", "--length", "--quiet", "--raw", "--status", "--strict", "--tag", "--untagged", "--warn", "--zero", "-a", "-c", "-l", "-w", "-z"],
  comm: ["--check-order", "--nocheck-order", "--output-delimiter", "--total", "--zero-terminated", "-1", "-2", "-3", "-z"],
  cp: ["--archive", "--attributes-only", "--backup", "--context", "--copy-contents", "--debug", "--dereference", "--force", "--interactive", "--keep-directory-symlink", "--link", "--no-clobber", "--no-dereference", "--no-preserve", "--no-target-directory", "--one-file-system", "--parents", "--preserve", "--recursive", "--reflink", "--remove-destination", "--sparse", "--strip-trailing-slashes", "--suffix", "--symbolic-link", "--target-directory", "--update", "--verbose", "-H", "-L", "-P", "-R", "-S", "-T", "-Z", "-a", "-b", "-d", "-f", "-i", "-l", "-n", "-p", "-r", "-s", "-t", "-u", "-v", "-x"],
  csplit: ["--digits", "--elide-empty-files", "--keep-files", "--prefix", "--quiet", "--silent", "--suffix-format", "--suppress-matched", "-b", "-f", "-k", "-n", "-s", "-z"],
  cut: ["--bytes", "--characters", "--complement", "--delimiter", "--fields", "--no-partial", "--only-delimited", "--output-delimiter", "--whitespace-delimited", "--zero-terminated", "-F", "-O", "-b", "-c", "-d", "-f", "-n", "-s", "-w", "-z"],
  date: ["--date", "--debug", "--file", "--iso-8601", "--reference", "--resolution", "--rfc-3339", "--rfc-email", "--set", "--universal", "--utc", "-I", "-R", "-d", "-f", "-r", "-s", "-u"],
  df: ["--all", "--block-size", "--exclude-type", "--human-readable", "--inodes", "--local", "--no-sync", "--output", "--portability", "--print-type", "--si", "--sync", "--total", "--type", "-B", "-H", "-P", "-T", "-a", "-h", "-i", "-k", "-l", "-t", "-x"],
  dir: ["--all", "--almost-all", "--author", "--block-size", "--classify", "--color", "--context", "--dereference", "--dereference-command-line", "--dereference-command-line-symlink-to-dir", "--directory", "--dired", "--escape", "--file-type", "--format", "--full-time", "--group-directories-first", "--hide", "--hide-control-chars", "--human-readable", "--hyperlink", "--ignore", "--ignore-backups", "--indicator-style", "--inode", "--kibibytes", "--literal", "--no-group", "--numeric-uid-gid", "--quote-name", "--quoting-style", "--recursive", "--reverse", "--show-control-chars", "--si", "--size", "--sort", "--tabsize", "--time", "--time-style", "--width", "--zero", "-1", "-C", "-S", "-U", "-X", "-c", "-g", "-l", "-m", "-o", "-p", "-t", "-u", "-v", "-x", "-A", "-B", "-D", "-F", "-G", "-H", "-I", "-L", "-N", "-Q", "-R", "-T", "-Z", "-a", "-b", "-d", "-f", "-h", "-i", "-k", "-n", "-q", "-r", "-s", "-w"],
  dircolors: ["--bourne-shell", "--c-shell", "--csh", "--print-database", "--print-ls-colors", "--sh", "-b", "-c", "-p"],
  dirname: ["--zero", "-z"],
  du: ["--all", "--apparent-size", "--block-size", "--bytes", "--count-links", "--dereference", "--dereference-args", "--exclude", "--exclude-from", "--files0-from", "--human-readable", "--inodes", "--max-depth", "--no-dereference", "--null", "--one-file-system", "--separate-dirs", "--si", "--summarize", "--threshold", "--time", "--time-style", "--total", "-0", "-A", "-B", "-D", "-H", "-L", "-P", "-S", "-X", "-a", "-b", "-c", "-d", "-h", "-k", "-l", "-m", "-s", "-t", "-x"],
  env: ["--argv0", "--block-signal", "--chdir", "--debug", "--default-signal", "--ignore-environment", "--ignore-signal", "--list-signal-handling", "--null", "--split-string", "--unset", "-0", "-C", "-S", "-a", "-i", "-u", "-v"],
  expand: ["--initial", "--tabs", "-i", "-t"],
  factor: ["--exponents", "-h"],
  fmt: ["--crown-margin", "--goal", "--prefix", "--split-only", "--tagged-paragraph", "--uniform-spacing", "--width", "-c", "-g", "-p", "-s", "-t", "-u", "-w"],
  fold: ["--bytes", "--characters", "--spaces", "--width", "-b", "-c", "-s", "-w"],
  head: ["--bytes", "--lines", "--quiet", "--silent", "--verbose", "--zero-terminated", "-c", "-n", "-q", "-v", "-z"],
  id: ["--context", "--group", "--groups", "--name", "--real", "--user", "--zero", "-G", "-Z", "-g", "-n", "-r", "-u", "-z"],
  install: ["--backup", "--compare", "--context", "--debug", "--directory", "--group", "--mode", "--no-target-directory", "--owner", "--preserve-context", "--preserve-timestamps", "--strip", "--strip-program", "--suffix", "--target-directory", "--verbose", "-C", "-D", "-S", "-T", "-Z", "-b", "-c", "-d", "-g", "-m", "-o", "-p", "-s", "-t", "-v"],
  join: ["--check-order", "--header", "--ignore-case", "--nocheck-order", "--zero-terminated", "-1", "-2", "-a", "-e", "-i", "-j", "-o", "-t", "-v", "-z"],
  kill: ["--list", "--signal", "--table", "-l", "-s", "-t"],
  ln: ["--backup", "--directory", "--force", "--interactive", "--logical", "--no-dereference", "--no-target-directory", "--physical", "--relative", "--suffix", "--symbolic", "--target-directory", "--verbose", "-F", "-L", "-P", "-S", "-T", "-b", "-d", "-f", "-i", "-n", "-r", "-s", "-t", "-v"],
  ls: ["--all", "--almost-all", "--author", "--block-size", "--classify", "--color", "--context", "--dereference", "--dereference-command-line", "--dereference-command-line-symlink-to-dir", "--directory", "--dired", "--escape", "--file-type", "--format", "--full-time", "--group-directories-first", "--hide", "--hide-control-chars", "--human-readable", "--hyperlink", "--ignore", "--ignore-backups", "--indicator-style", "--inode", "--kibibytes", "--literal", "--no-group", "--numeric-uid-gid", "--quote-name", "--quoting-style", "--recursive", "--reverse", "--show-control-chars", "--si", "--size", "--sort", "--tabsize", "--time", "--time-style", "--width", "--zero", "-1", "-C", "-S", "-U", "-X", "-c", "-g", "-l", "-m", "-o", "-p", "-t", "-u", "-v", "-x", "-A", "-B", "-D", "-F", "-G", "-H", "-I", "-L", "-N", "-Q", "-R", "-T", "-Z", "-a", "-b", "-d", "-f", "-h", "-i", "-k", "-n", "-q", "-r", "-s", "-w"],
  md5sum: HASH_HELP_OPTIONS,
  mkdir: ["--context", "--mode", "--parents", "--verbose", "-Z", "-m", "-p", "-v"],
  mkfifo: ["--context", "--mode", "-Z", "-m"],
  mknod: ["--context", "--mode", "-Z", "-m"],
  mktemp: ["--directory", "--dry-run", "--quiet", "--suffix", "--tmpdir", "-d", "-p", "-q", "-u"],
  mv: ["--backup", "--context", "--debug", "--exchange", "--force", "--interactive", "--no-clobber", "--no-copy", "--no-target-directory", "--strip-trailing-slashes", "--suffix", "--target-directory", "--update", "--verbose", "-S", "-T", "-Z", "-b", "-f", "-i", "-n", "-t", "-u", "-v"],
  nice: ["--adjustment", "-n"],
  nl: ["--body-numbering", "--footer-numbering", "--header-numbering", "--join-blank-lines", "--line-increment", "--no-renumber", "--number-format", "--number-separator", "--number-width", "--section-delimiter", "--starting-line-number", "-b", "-d", "-f", "-h", "-i", "-l", "-n", "-p", "-s", "-v", "-w"],
  nproc: ["--all", "--ignore"],
  numfmt: ["--debug", "--delimiter", "--field", "--format", "--from", "--from-unit", "--grouping", "--header", "--invalid", "--padding", "--round", "--suffix", "--to", "--to-unit", "--unit-separator", "--zero-terminated", "-d", "-z"],
  od: ["--address-radix", "--endian", "--format", "--output-duplicates", "--read-bytes", "--skip-bytes", "--strings", "--traditional", "--width", "-A", "-N", "-S", "-a", "-b", "-c", "-d", "-f", "-i", "-l", "-j", "-o", "-s", "-t", "-v", "-w", "-x"],
  paste: ["--delimiters", "--serial", "--zero-terminated", "-d", "-s", "-z"],
  pathchk: ["--portability", "-p", "-P"],
  pinky: ["--lookup", "-b", "-f", "-h", "-i", "-l", "-p", "-q", "-s", "-w"],
  pr: ["--across", "--columns", "--date-format", "--double-space", "--expand-tabs", "--first-line-number", "--form-feed", "--header", "--indent", "--join-lines", "--length", "--merge", "--no-file-warnings", "--number-lines", "--omit-header", "--omit-pagination", "--output-tabs", "--page-width", "--pages", "--sep-string", "--separator", "--show-control-chars", "--show-nonprinting", "--width", "-D", "-F", "-J", "-N", "-S", "-T", "-W", "-a", "-c", "-d", "-e", "-f", "-h", "-i", "-l", "-m", "-n", "-o", "-r", "-s", "-t", "-v", "-w"],
  printenv: ["--null", "-0"],
  ptx: ["--auto-reference", "--break-file", "--flag-truncation", "--format", "--gap-size", "--ignore-case", "--ignore-file", "--macro-name", "--only-file", "--references", "--right-side-refs", "--sentence-regexp", "--traditional", "--typeset-mode", "--width", "--word-regexp", "-A", "-F", "-G", "-M", "-R", "-S", "-W", "-b", "-f", "-g", "-i", "-o", "-r", "-t", "-w"],
  pwd: ["--logical", "--physical", "-L", "-P"],
  readlink: ["--canonicalize", "--canonicalize-existing", "--canonicalize-missing", "--no-newline", "--quiet", "--silent", "--verbose", "--zero", "-e", "-f", "-m", "-n", "-q", "-s", "-v", "-z"],
  realpath: ["--canonicalize", "--canonicalize-existing", "--canonicalize-missing", "--logical", "--no-symlinks", "--physical", "--quiet", "--relative-base", "--relative-to", "--strip", "--zero", "-E", "-L", "-P", "-e", "-m", "-q", "-s", "-z"],
  rm: ["--dir", "--force", "--interactive", "--no-preserve-root", "--one-file-system", "--preserve-root", "--recursive", "--verbose", "-I", "-R", "-d", "-f", "-i", "-r", "-v"],
  rmdir: ["--ignore-fail-on-non-empty", "--parents", "--verbose", "-p", "-v"],
  runcon: ["--compute", "--range", "--role", "--type", "--user", "-c", "-l", "-r", "-t", "-u"],
  seq: ["--equal-width", "--format", "--separator", "-f", "-s", "-w"],
  sha1sum: HASH_HELP_OPTIONS,
  sha224sum: HASH_HELP_OPTIONS,
  sha256sum: HASH_HELP_OPTIONS,
  sha384sum: HASH_HELP_OPTIONS,
  sha512sum: HASH_HELP_OPTIONS,
  sm3sum: HASH_HELP_OPTIONS,
  shred: ["--exact", "--force", "--iterations", "--random-source", "--remove", "--size", "--verbose", "--zero", "-f", "-n", "-s", "-u", "-v", "-x", "-z"],
  shuf: ["--echo", "--head-count", "--input-range", "--output", "--random-source", "--repeat", "--zero-terminated", "-e", "-i", "-n", "-o", "-r", "-z"],
  sort: ["--batch-size", "--buffer-size", "--check", "--compress-program", "--debug", "--dictionary-order", "--field-separator", "--files0-from", "--general-numeric-sort", "--human-numeric-sort", "--ignore-case", "--ignore-leading-blanks", "--ignore-nonprinting", "--key", "--merge", "--month-sort", "--numeric-sort", "--output", "--parallel", "--random-sort", "--random-source", "--reverse", "--sort", "--stable", "--temporary-directory", "--unique", "--version-sort", "--zero-terminated", "-C", "-M", "-R", "-S", "-T", "-V", "-b", "-c", "-d", "-f", "-g", "-h", "-i", "-k", "-m", "-n", "-o", "-r", "-s", "-t", "-u", "-z"],
  split: ["--additional-suffix", "--bytes", "--elide-empty-files", "--filter", "--hex-suffixes", "--line-bytes", "--lines", "--number", "--numeric-suffixes", "--separator", "--suffix-length", "--unbuffered", "--verbose", "-C", "-a", "-b", "-d", "-e", "-l", "-n", "-t", "-u", "-x"],
  stat: ["--cached", "--dereference", "--file-system", "--format", "--printf", "--terse", "-L", "-c", "-f", "-t"],
  stdbuf: ["--error", "--input", "--output", "-e", "-i", "-o"],
  stty: ["--all", "--file", "--save", "-F", "-a", "-g"],
  sync: ["--data", "--file-system", "-d", "-f"],
  tac: ["--before", "--regex", "--separator", "-b", "-r", "-s"],
  tail: ["--bytes", "--debug", "--follow", "--lines", "--max-unchanged-stats", "--pid", "--quiet", "--retry", "--silent", "--sleep-interval", "--verbose", "--zero-terminated", "-F", "-c", "-f", "-n", "-q", "-s", "-v", "-z"],
  tee: ["--append", "--ignore-interrupts", "--output-error", "-a", "-i", "-p"],
  timeout: ["--foreground", "--kill-after", "--preserve-status", "--signal", "--verbose", "-f", "-k", "-p", "-s", "-v"],
  touch: ["--date", "--no-create", "--no-dereference", "--reference", "--time", "-a", "-c", "-d", "-f", "-h", "-m", "-r", "-t"],
  tr: ["--complement", "--delete", "--squeeze-repeats", "--truncate-set1", "-C", "-c", "-d", "-s", "-t"],
  truncate: ["--io-blocks", "--no-create", "--reference", "--size", "-c", "-o", "-r", "-s"],
  tty: ["--quiet", "--silent", "-s"],
  uname: ["--all", "--hardware-platform", "--kernel-name", "--kernel-release", "--kernel-version", "--machine", "--nodename", "--operating-system", "--processor", "-a", "-i", "-m", "-n", "-o", "-p", "-r", "-s", "-v"],
  unexpand: ["--all", "--first-only", "--tabs", "-a", "-t"],
  uniq: ["--all-repeated", "--check-chars", "--count", "--group", "--ignore-case", "--repeated", "--skip-chars", "--skip-fields", "--unique", "--zero-terminated", "-D", "-c", "-d", "-f", "-i", "-s", "-u", "-w", "-z"],
  vdir: ["--all", "--almost-all", "--author", "--block-size", "--classify", "--color", "--context", "--dereference", "--dereference-command-line", "--dereference-command-line-symlink-to-dir", "--directory", "--dired", "--escape", "--file-type", "--format", "--full-time", "--group-directories-first", "--hide", "--hide-control-chars", "--human-readable", "--hyperlink", "--ignore", "--ignore-backups", "--indicator-style", "--inode", "--kibibytes", "--literal", "--no-group", "--numeric-uid-gid", "--quote-name", "--quoting-style", "--recursive", "--reverse", "--show-control-chars", "--si", "--size", "--sort", "--tabsize", "--time", "--time-style", "--width", "--zero", "-1", "-C", "-S", "-U", "-X", "-c", "-g", "-l", "-m", "-o", "-p", "-t", "-u", "-v", "-x", "-A", "-B", "-D", "-F", "-G", "-H", "-I", "-L", "-N", "-Q", "-R", "-T", "-Z", "-a", "-b", "-d", "-f", "-h", "-i", "-k", "-n", "-q", "-r", "-s", "-w"],
  wc: ["--bytes", "--chars", "--debug", "--files0-from", "--lines", "--max-line-length", "--total", "--words", "-L", "-c", "-l", "-m", "-w"],
  who: ["--all", "--boot", "--count", "--dead", "--heading", "--login", "--lookup", "--mesg", "--message", "--process", "--runlevel", "--short", "--time", "--users", "--writable", "-H", "-T", "-a", "-b", "-d", "-l", "-m", "-p", "-q", "-r", "-s", "-t", "-u", "-w"],
};
